language: go
go:
  - "1.9"
  - "1.10"
  - tip

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10.2

install:
  - go get -t -v ./...

script:
  - ./.travis-scripts/test.sh
  - golangci-lint run

after_success:
  - bash <(curl -s https://codecov.io/bash)
